version: "3.8"
services:
  snaketestapp:
    image: schbros/chatappsonarpipe:latest
    build: .
    container_name: chatappzap
    ports: 
      - "80:3700"
    environment:
      - PORT=3700
    volumes:
      - ./:/app
    
